// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwaJbkaw_p1LtDcs2uG3TUJ6sz3L5n2i8',
    appId: '1:254964195041:android:2b7ae6fbc41ded9e3fa1a0',
    messagingSenderId: '254964195041',
    projectId: 'chathitoryai',
    storageBucket: 'chathitoryai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBByBBqZeC02bqY2K6hqd0DymrX4sW6HWM',
    appId: '1:254964195041:ios:65784b2240995d023fa1a0',
    messagingSenderId: '254964195041',
    projectId: 'chathitoryai',
    storageBucket: 'chathitoryai.firebasestorage.app',
    androidClientId: '254964195041-u91qamu5mkrcv6rpvkbgli0c2865rqd5.apps.googleusercontent.com',
    iosClientId: '254964195041-mug22dccsl70c8l367s69vmhd5r3gheg.apps.googleusercontent.com',
    iosBundleId: 'com.pro.historyAi',
  );
}
